export enum CharacterExpressions {
  Default = 'default',
  Hit = 'hit',
  Smile = 'smile',
  Troubled = 'troubled',
  Cry = 'cry',
  Angry = 'angry',
  Bewildered = 'bewildered',
  Stunned = 'stunned',
  /* cash */
  Hum = 'hum',
  Despair = 'despair',
  Oops = 'oops',
  Vomit = 'vomit',
  Bowing = 'bowing',
  Dam = 'dam',
  Pain = 'pain',
  Hot = 'hot',
  Cheers = 'cheers',
  Wink = 'wink',
  Blaze = 'blaze',
  Chu = 'chu',
  Shine = 'shine',
  Glitter = 'glitter',
  Love = 'love',
  /* gms */
  QBlue = 'qBlue',
}
